---
- name: install php & depend packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php7.2
    - php7.2-common
    - php7.2-cli
    - php7.2-fpm
    - php7.2-mysql
    - php7.2-dev
    - php7.2-mbstring
    - php7.2-zip
    - php7.2-xml
    - php7.2-sqlite
