---
- name: install python depend package
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - python3-pip
    - python3-dev
    - libssl-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
