---
- name: install ruby
  apt:
    name: ruby

- name: install ruby depend packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libreadline6-dev
    - libyaml-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm5
    - libgdbm-dev
